from util.load_env import load

SQLALCHEMY_DATABASE_URI = load("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

SECRET_KEY = load('SECRET_KEY', 'my_secret')

BCRYPT_LOG_ROUNDS = 13