from os import getenv, path

SQLALCHEMY_DATABASE_URI = getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

SECRET_KEY = getenv('SECRET_KEY', 'my_secret')

BCRYPT_LOG_ROUNDS = 13