version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] %(name)s - %(message)s (%(filename)s:%(funcName)s:%(lineno)d)'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file:
        class : logging.handlers.RotatingFileHandler
        formatter: simple
        level: DEBUG
        filename: logs/logs.log
        maxBytes: 1000000
        backupCount: 3
loggers:
  app:
    level: DEBUG
    handlers: [console,file]
    propagate: yes
